name: Request administrator permission in the repository
description: Allows the RBMH DPS Tech Team Internal members to request temporary admin permission in a repository
title: Request administrator permission
labels: ["permission-request"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the form the request administrator permissions in the repository
  - type: textarea
    id: reason
    attributes:
      label: Reason
      description: Tell us why you need administrator permissions.
    validations:
      required: true
  - type: dropdown
    id: expiration
    attributes:
      label: Expiration
      description: How long do you need administrator permissions?
      options:
        - 1h
        - 2h
    validations:
      required: true
